name: Build

on:
  push:
    tags:
    - "*"

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
    
      - uses: webfactory/ssh-agent@v0.9.0
        id: ssh
        with:
          ssh-private-key: ${{ secrets.SIGNER_KEY }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}