name: Validate And Test

on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - "README.md"
    - ".dockerignore"
    - ".goreleaser.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
          cache: true
      
      - uses: docker/setup-buildx-action@v3
      
      - name: Verify dependencies
        run: go mod verify
      
      - name: Run vet 
        run: go vet ./...
      
      - name: Run build 
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...